### ISSUE TITLE
can it be installed with the UPM>git url?

### ISSUE THREAD

**Issue by laurentopia** [neon-age/Smart-Inspector#1]
I tried a few formats and got errors so maybe not
![image](https://user-images.githubusercontent.com/26075468/122096748-bab9fd00-cdc3-11eb-9e12-9cad75ee0e5a.png)

**Comment by neon-age** [comment]
it should be https://github.com/neon-age/Smart-Inspector.git

**Comment by laurentopia** [comment]
thanks, I always forget the .git
