### ISSUE TITLE
Can't build Game

### ISSUE THREAD

**Issue by Ogoku** [neon-age/Smart-Inspector#18]
Hey @neon-age,

when I build my game I got these messages in my console:
![image](https://user-images.githubusercontent.com/11227196/128607136-f7ef2165-38a6-41c0-b56a-d2f8b91d17ec.png)

**Comment by neon-age** [comment]
Install latest v0.8.0-pre.1

**Comment by Ogoku** [comment]
Yeah! That helped :) Thx.
