### ISSUE TITLE
might be incompatible with 2020.1.17?

### ISSUE THREAD

**Issue by laurentopia** [neon-age/Smart-Inspector#2]
![image](https://user-images.githubusercontent.com/26075468/122098142-4da76700-cdc5-11eb-971b-5e5235c065ed.png)

**Comment by neon-age** [comment]
Sheesh, that might be Unity's bug I'm encountering with styleSheets being unloaded when referencing them from ScriptableObject.
Try to recompile anything, should help

**Comment by laurentopia** [comment]
yes, recompiling did help. got that left lingering in the console afterward, not crippling though
![image](https://user-images.githubusercontent.com/26075468/122098788-21401a80-cdc6-11eb-8fea-528a915cf5c3.png)

**Comment by neon-age** [comment]
Oh, this line needs to be removed

**Comment by laurentopia** [comment]
nah, still blowing up
![image](https://user-images.githubusercontent.com/26075468/122099121-7da33a00-cdc6-11eb-8299-174b85784a3c.png)

**Comment by neon-age** [comment]
Strange, I'll look into this tomorrow

**Comment by digiwombat** [comment]
Same issue on 2021.1.11f.

**Comment by neon-age** [comment]
All should be now fixed in v0.3.0!

**Comment by neon-age** [comment]
May I close this?

**Comment by digiwombat** [comment]
Appears fixed for me in 2021.1.11f.

**Comment by laurentopia** [comment]
in 2020.1.17 what doesn't work: clicking on a tab doesn't open the inspector at that tab like on the video
what works: error free, new events, easier drag and drop

**Comment by neon-age** [comment]
doesn't open? can you record a video?

**Comment by laurentopia** [comment]
no but i can show you what open means:
i click on that last tab and nothing happens:
![image](https://user-images.githubusercontent.com/26075468/122430978-e4e8f780-cf48-11eb-8791-18cf0d4116c6.png)

**Comment by neon-age** [comment]
Strange indeed, every other version works alright. I'll have to install it now..

**Comment by laurentopia** [comment]
a thought: could be because all the components are the same, just with different content

**Comment by laurentopia** [comment]
correction: the last component which i pressed on wasn't an ult event so that's not it

**Comment by neon-age** [comment]
Turns out 2020.1. tab toggle had the same broken behaviour as in 2019.4.. But might it be also the case in 2020.2!?

**Comment by laurentopia** [comment]
there is this error that happens in v0.3 every now and then, now idea what triggers it
![image](https://user-images.githubusercontent.com/26075468/122488847-34ecac00-cf93-11eb-89a4-ebffc5f0ef61.png)

**Comment by neon-age** [comment]
I think I also caught this one, happened when EditorElement became null and I tried to access it during layout callback

**Comment by neon-age** [comment]
This layout callback also gets registered multiple times on editors list change !! 😲

**Comment by laurentopia** [comment]
> This layout callback also gets registered multiple times on editors list change !! 😲

this sounds expensive, is this how unity does things?

**Comment by neon-age** [comment]
No, it was my mistake and already fixed :)
I'm currently refactoring injection & setup code, so it's all in one place, error-free and easily extendable with public API.
You can join Discord for more info 😄

**Comment by laurentopia** [comment]
nice! I'll update and join

**Comment by laurentopia** [comment]
is it still 0.3 the new version? UPM doesn't detect an update

**Comment by neon-age** [comment]
Yes, if you imported using OpenUPM it will show all verified releases.
v0.5.0 release is planned for today's evening :)
