### ISSUE TITLE
Can't build in 2021.2^ because package contains unused Editor using code.

### ISSUE THREAD

**Issue by Creta5164** [neon-age/Smart-Inspector#24]
![image](https://user-images.githubusercontent.com/13521406/144800569-9fccf517-cc86-4a6a-b79f-ae45ea4625d7.png)

I just tried to update our project to `2021.2^`, it can't build package contains unused Editor using code.  
It seems someone already created PR on #19, please review this one.

**Comment by neon-age** [comment]
Merged

**Comment by Creta5164** [comment]
Thanks for your hard work and attention about this, I'll close this issue.
