### ISSUE TITLE
CLI batchMode breaks when Smart-Inspector is in the project

### ISSUE THREAD

**Issue by zoeesilcock** [neon-age/Smart-Inspector#5]
This is a weird one so I've no idea what it could be about but I'm throwing it out there because it's a deal breaker for us since it breaks our CI pipeline.

After adding Smart-Inspector to the project we can no longer run methods from the CLI using batchMode, everything times out after 5 minutes of being idle. It doesn't seem to matter what happens in the method, I have tried with a method that simply outputs a `Debug.Log` and it still doesn't work while Smart-Inspector is in the project.

I have tried both adding the plugin using a Git URL in Package Manager and by simply adding the directory to the project manually so I don't think it's related to the Package Manager.

Example command:
```
"C:\Program Files\Unity\Hub\Editor\2019.4.26f1\Editor\Unity.exe" -batchmode -projectPath / -nographics -executeMethod Custom.MyBuildScript.Build -silent-crashes -quit -logFile build.log
```

Output from batchMode:
```
Aborting batchmode due to failure:
Timeout while executing 'executeMethod' method 'Custom.MyBuildScript.Build'.
```

**Comment by neon-age** [comment]
I have no idea what CLI batchMode is or does. Is there anything related in Editor Logs?
Such issue might occur because of Harmony patching. Could you try modifying Patcher.cs so it is not executed on InitializeOnLoad?

**Comment by zoeesilcock** [comment]
There was no more info in the editor log, it just sits idle once it reaches the `executeMethod` step and then hits a timeout after 5 minutes and outputs the message I posted.

Batch mode is for running Unity from the command line, in our case we use this in order to generate our builds in an automated way on a different machine than where we work. For testing purposes it is enough to make a simple static method which outputs to the Debug.Log. There is more info about batch mode here: https://docs.unity3d.com/Manual/CommandLineArguments.html

I did a quick test now and it appears to work when I comment out that `InitializeOnLoad` so I would suggest using this to avoid running Smart-Inspector in batch mode: https://docs.unity3d.com/ScriptReference/Application-isBatchMode.html

**Comment by neon-age** [comment]
Thanks for the info! I remember having infinite import time issue on Editor launch with asset operations inside InitializeOnLoad, which I've fixed with EditorApplication.delayCall. Anyway, adding the check to the Patcher

**Comment by neon-age** [comment]
Was it resolved?

**Comment by zoeesilcock** [comment]
Yes, I can confirm that the `Application.isBatchMode` check fixed the issue. Thanks!
